config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  resources :images

  get 'probar', to: 'control#saludo'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :picture, PictureUploader
  validates :description, presence:true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
  def saludo
    @miNombre = 'Xavier'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @colFotos = Image.all
  end

  def new
    @Foto = Image.new
  end

  def create
    #render plain: params[:image].inspect
    @Foto = Image.new image_params
    if @Foto.save
      return redirect_to images_path
    end
    render :new

  end

  def edit

  end

  def update
    @Foto.update image_params
    redirect_to @Foto
  end

  def destroy
    @Foto.destroy
    redirect_to images_path
  end

  def show

  end

  private

  def set_image
    @Foto = Image.find params[:id]
  end

  def image_params
    params.require(:image).permit :description, :picture
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/control/saludo.html.erb
<p>Hola desde el controlador soy: <%= @miNombre%> </p>

app/views/home/index.html.erb
<% if user_signed_in? %>
    <h1>Bienvenido <%= current_user.email %></h1>
<% else %>
    <h1>RailsGram</h1>
<%end%>

app/views/images/_form.html.erb
<div class="form-group">
  <%= form_for @Foto, builder: CustomFormBuilder do |f| %>
      <%= f.form_error%>
      <%= f.label :description %> <br>
      <%= f.text_field :description, class: 'form-control' %>
      <%= f.field_error :description %>
      <br>
      <%= f.label :picture %> <br>
      <%= f.file_field :picture, class: 'form-control' %>
      <br>
      <%= f.submit 'Enviar', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/images/_image.html.erb
<div class="col-4">
  <figure class="figure">
    <%= image_tag image.picture.thumb.url, class:'figure-img img-fluid rounded'%>
    <figcaption class="figure-caption"><%= image.description %>
      <%= link_to t('.edit_link'), edit_image_path(image) %>
      <%= link_to t('.remove_link'), image, method: :delete, data:{ confirm: 'sure?'} %>
    </figcaption>
  </figure>
  <br>
</div>

app/views/images/edit.html.erb
<div class="container">
  <p> Editar imagen </p>
  <%= render 'form' %>
</div>

app/views/images/index.html.erb
<div class="container">
  <div class="row">
    <%= render @colFotos %>
  </div>
</div>

app/views/images/new.html.erb
<div class="container">
  <p> Hola desde la vista NEW</p>
  <%= render 'form' %>
</div>

app/views/images/show.html.erb
<div class="container">
  <p> Vista Show</p>
  <%= image_tag @Foto.picture.thumb.url, class:'figure-img img-fluid rounded'%>
  <%= @Foto.description %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav justify-content-end">
      <%- if user_signed_in? %>
        <li class="nav-item">
          <%= link_to '*Salir ', destroy_user_session_path, method: :delete %>
        </li>
      <%else%>
        <li>
          <%= link_to '*Iniciar ', new_user_session_path %>
        </li>
        <li>
          <%= link_to '*Registrarme ', new_user_registration_path %>
        </li>
      <% end%>
    </ul>
    <div class="container">
      <p class="alert"><%= alert %></p>
      <p class="notice"><%= notice %></p>
    <%= yield %></div>
  </body>
</html>